config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

    devise_for :alumnos
    resources :venta
    devise_for :users
    resources :depositos
    resources :monederos
    resources :students

    root 'welcome#index'

    resources :update_stocks
    resources :stocks
    resources :products
    resources :products
    resources :products

    authenticated :user do
        root 'dashboard#index',as: :user_root
    end

    authenticated :alumno do
        root 'dashboard2#index',as: :alumno_root
    end

end

app/models/update_stock.rb
class UpdateStock < ActiveRecord::Base
  belongs_to :product
end

app/controllers/update_stocks_controller.rb
class UpdateStocksController < ApplicationController
  before_action :set_update_stock, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /update_stocks
  # GET /update_stocks.json
  def index
    @update_stocks = UpdateStock.all
  end

  # GET /update_stocks/1
  # GET /update_stocks/1.json
  def show
  end

  # GET /update_stocks/new
  def new
    @update_stock = UpdateStock.new
    @products = Product.all
  end

  # GET /update_stocks/1/edit
  def edit
  end

  # POST /update_stocks
  # POST /update_stocks.json
  def create
    @update_stock = UpdateStock.new(update_stock_params)

    respond_to do |format|
      if @update_stock.save
        @stock = Stock.find_by(product: @update_stock.product)
        @stock.cantidad = @stock.cantidad + @update_stock.cantidad
        @stock.save
        format.html { redirect_to @update_stock, notice: 'Update stock was successfully created.' }
        format.json { render :show, status: :created, location: @update_stock }
      else
        format.html { render :new }
        format.json { render json: @update_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /update_stocks/1
  # PATCH/PUT /update_stocks/1.json
  def update
    respond_to do |format|
      if @update_stock.update(update_stock_params)
        format.html { redirect_to @update_stock, notice: 'Update stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @update_stock }
      else
        format.html { render :edit }
        format.json { render json: @update_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /update_stocks/1
  # DELETE /update_stocks/1.json
  def destroy
    @update_stock.destroy
    respond_to do |format|
      format.html { redirect_to update_stocks_url, notice: 'Update stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update_stock
      @update_stock = UpdateStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_stock_params
      params.require(:update_stock).permit(:product_id, :cantidad)
    end
end

app/helpers/update_stocks_helper.rb
module UpdateStocksHelper
end

app/views/update_stocks/_form.html.erb
<%= form_for(@update_stock) do |f| %>
  <% if @update_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update_stock.errors.count, "error") %> prohibited this update_stock from being saved:</h2>

      <ul>
      <% @update_stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Producto' %><br><%= collection_select(:update_stock,:product_id, @products, :id, :nombre, {prompt: false,class:"col-md-2 control-label"}) %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/update_stocks/edit.html.erb
<h1>Editing Update Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @update_stock %> |
<%= link_to 'Back', update_stocks_path %>

app/views/update_stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ultimas Recepciones</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Product</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @update_stocks.each do |update_stock| %>
      <tr>
        <td><%= update_stock.product.nombre %></td>
        <td><%= update_stock.cantidad %></td>
        <td><%= link_to 'Show', update_stock %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Update stock', new_update_stock_path %>

app/views/update_stocks/new.html.erb
<h1>New Update Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', update_stocks_path %>

app/views/update_stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @update_stock.product.nombre %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @update_stock.cantidad %>
</p>

<%= link_to 'Back', update_stocks_path %>