config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

    devise_for :alumnos
    resources :venta
    devise_for :users
    resources :depositos
    resources :monederos
    resources :students

    root 'welcome#index'

    resources :update_stocks
    resources :stocks
    resources :products
    resources :products
    resources :products

    authenticated :user do
        root 'dashboard#index',as: :user_root
    end

    authenticated :alumno do
        root 'dashboard2#index',as: :alumno_root
    end

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :student
end

app/models/deposito.rb
class Deposito < ActiveRecord::Base
  belongs_to :student
end

app/models/monedero.rb
class Monedero < ActiveRecord::Base
  belongs_to :student
end

app/models/product.rb
class Product < ActiveRecord::Base
    mount_uploader :imagen, ImageUploader

    validates_processing_of :imagen
    validate :image_size_validation

    private
    def image_size_validation
        errors[:imagen] << "should be less than 500KB" if imagen.size > 0.5.megabytes
    end
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
end

app/models/student.rb
class Student < ActiveRecord::Base
    mount_uploader :imagen, ImageUploader

    validates_processing_of :imagen
    validate :image_size_validation

    has_many :alumno

    private
    def image_size_validation
        errors[:imagen] << "should be less than 500KB" if imagen.size > 0.5.megabytes
    end


end

app/models/update_stock.rb
class UpdateStock < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :student
  belongs_to :product
end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
    before_action :set_ventum, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    # GET /venta
    # GET /venta.json
    def index
        @venta = Ventum.all
    end

    # GET /venta/1
    # GET /venta/1.json
    def show
    end

    # GET /venta/new
    def new
        @ventum = Ventum.new
        @students = Student.all
        @products = Product.all
    end

    # GET /venta/1/edit
    def edit
    end

    # POST /venta
    # POST /venta.json
    def create
        @ventum = Ventum.new(ventum_params)

        respond_to do |format|
            if @ventum.save
                @monedero = Monedero.find_by(student: @ventum.student)
                @monedero.cantidad = @monedero.cantidad - (@ventum.product.precio * @ventum.cantidad)
                @monedero.save

                @stock = Stock.find_by(product: @ventum.product)
                @stock.cantidad = @stock.cantidad - @ventum.cantidad
                @stock.save
                format.html { redirect_to @ventum, notice: 'Ventum was successfully created.' }
                format.json { render :show, status: :created, location: @ventum }
            else
                format.html { render :new }
                format.json { render json: @ventum.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /venta/1
    # PATCH/PUT /venta/1.json
    def update
        respond_to do |format|
            if @ventum.update(ventum_params)
                format.html { redirect_to @ventum, notice: 'Ventum was successfully updated.' }
                format.json { render :show, status: :ok, location: @ventum }
            else
                format.html { render :edit }
                format.json { render json: @ventum.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /venta/1
    # DELETE /venta/1.json
    def destroy
        @ventum.destroy
        respond_to do |format|
            format.html { redirect_to venta_url, notice: 'Ventum was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventum
        @ventum = Ventum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventum_params
        params.require(:ventum).permit(:student_id, :product_id, :cantidad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard2_helper.rb
module Dashboard2Helper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/depositos_helper.rb
module DepositosHelper
end

app/helpers/monederos_helper.rb
module MonederosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <% if user_signed_in? %>
                <%= link_to 'ProtoType 1',user_root_path, class:"navbar-brand"  %>
            <% else %>
                <%= link_to 'ProtoType 3',root_path, class:"navbar-brand"  %>
            <% end %>
        </div>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <% if user_signed_in? %>
            <ul class="nav navbar-nav">
                <li class="active"><%= link_to 'Venta',new_ventum_path %></li>
                <li class="dropdown">
                    <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Productos
                        <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'productos', products_path%></li>
                            <li><%= link_to 'Inventario', stocks_path%></li>
                            <li class="divider"></li>

                        </ul>
                    </li>
                    <li><%= link_to 'Recepcion de productos', new_update_stock_path %></li>
                    <li class="dropdown">
                        <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Alumnos
                            <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'Alumnos', students_path%></li>
                                <li><%= link_to 'Monederos', monederos_path%></li>
                                <li class="divider"></li>
                            </ul>
                        </li>
                        <li><%= link_to 'Realizar Deposito', new_deposito_path%></li>
                    </ul>
                    <% end %>
                    <ul class="nav navbar-nav navbar-right">
                        <% if user_signed_in? %>
                        <li class="dropdown">
                            <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                            </ul>
                        </li>
                        <% else %>
                            <li ><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                            <li ><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                            <li ><%= link_to "Acceso Alumnos", new_alumno_session_path, :class => 'navbar-link'  %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>

app/views/layouts/_nav2.html.erb
<div class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <% if alumno_signed_in? %>
                <%= link_to 'ProtoType',alumno_root_path, class:"navbar-brand"  %>
            <% else %>
                <%= link_to 'ProtoType',root_path, class:"navbar-brand"  %>
            <% end %>
        </div>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <% if alumno_signed_in? %>
                        <li class="dropdown">
                            <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_alumno.email %>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'Edit profile', edit_alumno_registration_path, :class => 'navbar-link' %></li>
                                <li><%= link_to "Logout", destroy_alumno_session_path, method: :delete, :class => 'navbar-link'  %></li>
                            </ul>
                        </li>
                        <% else %>
                            <li ><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                            <li ><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                            <li ><%= link_to "Acceso Alumnos", new_alumno_session_path, :class => 'navbar-link'  %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Uteche</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
    <% if user_signed_in? %>
        <%= render 'layouts/nav'%>
    <% elsif alumno_signed_in? %>
        <%= render 'layouts/nav2'%>
    <% else %>
        <%= render 'layouts/nav'%>
    <% end %>


    <%= yield %>

</body>
</html>